"""baseline: all 8 tables

Revision ID: 2a912a3d181d
Revises: 
Create Date: 2026-03-22 18:07:08.828572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a912a3d181d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('client_host', sa.String(length=45), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_user_id'), 'action_logs', ['user_id'], unique=False)
    op.create_index('ix_action_logs_user_ts', 'action_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('manual_reports',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('associated_task_ids', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_reports_user_id'), 'manual_reports', ['user_id'], unique=False)
    op.create_table('session_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('task_name', sa.String(length=256), nullable=True),
    sa.Column('goal_minutes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_logs_user_ended', 'session_logs', ['user_id', 'ended_at'], unique=False)
    op.create_index(op.f('ix_session_logs_user_id'), 'session_logs', ['user_id'], unique=False)
    op.create_table('synthesis_reports',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('commitment_score', sa.Integer(), nullable=False),
    sa.Column('suggested_tasks', sa.Text(), nullable=True),
    sa.Column('llm_run_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthesis_reports_user_id'), 'synthesis_reports', ['user_id'], unique=False)
    op.create_table('system_states',
    sa.Column('mode_type', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('requires_recovery', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_states_user_id'), 'system_states', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_usage_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('llm_run_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_chars', sa.Integer(), nullable=False),
    sa.Column('was_mocked', sa.Boolean(), nullable=False),
    sa.Column('week_number', sa.String(length=8), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_endpoint'), 'ai_usage_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_endpoint'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_system_states_user_id'), table_name='system_states')
    op.drop_table('system_states')
    op.drop_index(op.f('ix_synthesis_reports_user_id'), table_name='synthesis_reports')
    op.drop_table('synthesis_reports')
    op.drop_index(op.f('ix_session_logs_user_id'), table_name='session_logs')
    op.drop_index('ix_session_logs_user_ended', table_name='session_logs')
    op.drop_table('session_logs')
    op.drop_index(op.f('ix_manual_reports_user_id'), table_name='manual_reports')
    op.drop_table('manual_reports')
    op.drop_index('ix_action_logs_user_ts', table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_user_id'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
